### ISSUE TITLE
badges that were created using badger.openbadges.org instance generate error when sending to backpack

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadger#328]
This bug was reported by the folks at DigitalMe. 

![screen shot 2013-12-09 at 18 39 14](https://f.cloud.github.com/assets/1424627/1710242/eff57e24-612c-11e3-88e3-ae02dfc9c7bb.png)

**Comment by stenington** [comment]
Example assertion: http://badger.openbadges.org/badge/assertion/39841d20863cda3d5c2e8fab6f0b0c1d93b79373

**Comment by stenington** [comment]
The backpack's unhappy while the validator says it's fine because they're using different versions of the underlying validation library. :astonished:

The backpack is blowing up saying `'recipient.salt': { [Error: must be a string] message: 'must be a string', code: undefined }` which is technically incorrect. The spec says the salt is optional.

**Comment by stenington** [comment]
I think the work to be done is:
- [x] update the validator to make salts optional, if that's not how it is: mozilla/openbadges-validator#24
- [x] update the version of the validator used in the validator service: mozilla/openbadges-validator-service#24
- [x] update the version of the validator used in the backpack to include the fix above: PR mozilla/openbadges#974
- [x] move the validator-service and backpack to staging and production

**Comment by stenington** [comment]
@threeqube As a first step at improving error messaging, what's a better generic error message than "undefined"?

**Comment by threeqube** [comment]
@stenington well why does this error occur?

**Comment by stenington** [comment]
@threeqube Well, I was thinking of putting in a better generic message, not a specific message for this actual problem. I think it'll get covered in one of the many open tickets to make our error messaging better though.

**Comment by threeqube** [comment]
How about, "We have encountered an issue. Please try again later."?

**Comment by iamjessklein** [comment]
+1 @stenington - I wrote a bunch of tickets on error messages. I do like that suggestion in the interim @threeqube
